// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exam struct {
	ID           int32
	LessonID     pgtype.Int4
	Title        string
	MaxScore     pgtype.Int4
	StudentScore pgtype.Int4
	ExamUrl      pgtype.Text
}

type Exercise struct {
	ID           int32
	LessonID     pgtype.Int4
	Title        string
	MaxScore     pgtype.Int4
	StudentScore pgtype.Int4
	ExerciseUrl  pgtype.Text
}

type File struct {
	ID         int32
	GroupID    pgtype.Int4
	UploadedBy pgtype.Int4
	FilePath   string
	UploadedAt pgtype.Timestamp
}

type Group struct {
	ID       int32
	Name     string
	Trophies pgtype.Int4
}

type Leaderboard struct {
	GroupID       int32
	GroupName     string
	TotalTrophies int64
}

type Lesson struct {
	ID        int32
	Title     string
	SubjectID pgtype.Int4
	GroupID   pgtype.Int4
	Completed pgtype.Bool
	LessonUrl pgtype.Text
}

type Message struct {
	ID        int32
	GroupID   pgtype.Int4
	SenderID  pgtype.Int4
	Message   string
	CreatedAt pgtype.Timestamp
}

type Subject struct {
	ID   int32
	Name string
}

type Trophy struct {
	ID       int32
	GroupID  pgtype.Int4
	LessonID pgtype.Int4
	EarnedAt pgtype.Timestamp
	Amount   pgtype.Int4
}

type User struct {
	ID       int32
	Name     pgtype.Text
	Email    string
	Password string
	Role     pgtype.Text
	GroupID  pgtype.Int4
}
